name: codecov

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3.8 -m pip install pytest==6.1.2 flake8==3.8.4 numpy==1.11 codecov==2.1.10 pytest-cov==2.10.1
    - name: Run checks/test
      run: |
        flake8 --max-line-length 119 .
        PYTHONPATH=. pytest --cov-report=xml --cov=visual_peaks_AP
    - name: Upload codecov
      uses: codecov/codecov-action@v1
      with:
        file: coverage.xml
        name: codecov-master
        fail_ci_if_error: true
        verbose: true
