name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Install python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pytest
      run: |
        python${{ matrix.python-version }} -m pip install pytest==6.1.2 flake8==3.8.4 codecov==2.1.10
    - name: Run checks/test
      run: |
        flake8 .
        PYTHONPATH=. pytest
        codecov --file coverage/lcov.info --disable search

